## J.J. Thomson e/m Lab

### Alexandra Higley

In [1]:
import numpy as np
from scipy.optimize import curve_fit
from pylab import *
from math import e
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import scipy
from scipy import stats
from scipy.stats import norm

Let's work with Experimenter One's data first:

### Experimenter One

In [2]:
# I -> current through coils in amps (measured)*
# a -> mean radius of coil in meters
# N -> number of turns of wire on each coil 
# r -> radius of circle in meters (measured)*
# V -> potential difference in Volts (measured)*

perm = (4*np.pi)*(10**-7)
cons = 2.47*(10**12)
N = 132
a = 0.1475 #m

In [3]:
def em(V,I,r):
    em_term = (cons*((a**2)/(N**2))*((V)/((I**2)*(r**2))))
    return em_term

In [4]:
r = (0.025, 0.0275, 0.03, 0.0325, 0.035, 0.0375, 0.04, 0.0425, 0.045, 0.0475, 0.05, 0.0525, 0.055)#m

V = (200, 250, 300, 350, 400, 450, 500) #V

In [5]:
#200 Volts
I1_1ew = (2.35,2.13, 1.97, 1.81, 1.69, 1.58, 1.48, 1.4, 1.32, 1.25, 1.2, 1.12, 1.06)
I1_1ns = (2.45, 2.28, 2.11, 2, 1.88, 1.72, 1.56, 1.49, 1.4, 1.33, 1.25, 1.17, 1.1)

#250 Volts
I1_2ew = (2.65, 2.39, 2.21, 2.03, 1.9, 1.77, 1.66, 1.56, 1.49, 1.4, 1.34, 1.27, 1.22)
I1_2ns = (2.79, 2.6, 2.42, 2.29, 2.19, 1.98, 1.82, 1.7, 1.55, 1.5, 1.41, 1.36, 1.25)

#300 Volts
I1_3ew = (2.9, 2.62, 2.42, 2.22, 2.07, 1.94, 1.82, 1.71, 1.63, 1.54, 1.48, 1.4, 1.33)
I1_3ns = ((10, 2.79,2.65, 2.5, 2.38, 2.22, 2.02, 1.85, 1.74, 1.66, 1.56, 1.44, 1.37)) #first term N/A, using 10 as place holder

#350 Volts
I1_4ew = (10, 2.28, 2.62, 2.4, 2.25, 2.09, 1.97, 1.84, 1.75, 1.66, 1.59, 1.51, 1.44) #first term N/A
I1_4ns = (10, 2.74, 2.82, 2.51, 2.39, 2.26, 2.11, 1.99, 1.83, 1.77, 1.66, 1.54, 1.44) #first term N/A

#400 Volts
I1_5ew = (10, 10, 2.76, 2.56, 2.39, 2.22, 2.09, 1.96, 1.87, 1.77, 1.64, 1.6, 1.54) #first two terms N/A
I1_5ns = (10, 10, 2.92, 2.7, 2.51, 2.39, 2.25, 2.16, 2.08, 1.96, 1.8, 1.7, 1.66) #first two terms N/A

#450 Volts
I1_6ew = (10, 10, 2.95, 2.71, 2.53, 2.35, 2.21, 2.08, 1.97, 1.86, 1.78, 1.7, 1.62) #first two terms N/A
I1_6ns = (10, 10, 10, 2.99, 2.75, 2.55, 2.43, 2.2, 2.08, 1.97, 1.9, 1.81, 1.69) #first three terms N/A

#500 Volts
I1_7ew = (10, 10, 10, 2.85, 2.67, 2.49, 2.34, 2.18, 2.07, 1.95, 1.88, 1.78, 1.71) #first three terms N/A
I1_7ns = (10, 10, 10, 10, 2.85, 2.6, 2.44, 2.27, 2.2, 2.08, 1.99, 1.89, 1.78) #first four terms N/A

In [6]:
#200 Volts
#I1_1ew = (2.35, 2.13, 1.97, 1.81, 1.69, 1.58, 1.48, 1.4, 1.32, 1.25, 1.2, 1.12, 1.06)
#I1_1ns = (2.45, 2.28, 2.11, 2, 1.88, 1.72, 1.56, 1.49, 1.4, 1.33, 1.25, 1.17, 1.1)

#250 Volts
#I1_2ew = (2.65, 2.39, 2.21, 2.03, 1.9, 1.77, 1.66, 1.56, 1.49, 1.4, 1.34, 1.27, 1.22)
#I1_2ns = (2.79, 2.6, 2.42, 2.29, 2.19, 1.98, 1.82, 1.7, 1.55, 1.5, 1.41, 1.36, 1.25)

#300 Volts
#I1_3ew = (2.9, 2.62, 2.42, 2.22, 2.07, 1.94, 1.82, 1.71, 1.63, 1.54, 1.48, 1.4, 1.33)
#I1_3ns = ((2.79,2.65, 2.5, 2.38, 2.22, 2.02, 1.85, 1.74, 1.66, 1.56, 1.44, 1.37)) #first term N/A, using 10 as place holder

#350 Volts
#I1_4ew = (2.28, 2.62, 2.4, 2.25, 2.09, 1.97, 1.84, 1.75, 1.66, 1.59, 1.51, 1.44) #first term N/A
#I1_4ns = (2.74, 2.82, 2.51, 2.39, 2.26, 2.11, 1.99, 1.83, 1.77, 1.66, 1.54, 1.44) #first term N/A

#400 Volts
#I1_5ew = (2.76, 2.56, 2.39, 2.22, 2.09, 1.96, 1.87, 1.77, 1.64, 1.6, 1.54) #first two terms N/A
#I1_5ns = (2.92, 2.7, 2.51, 2.39, 2.25, 2.16, 2.08, 1.96, 1.8, 1.7, 1.66) #first two terms N/A

#450 Volts
#I1_6ew = (2.95, 2.71, 2.53, 2.35, 2.21, 2.08, 1.97, 1.86, 1.78, 1.7, 1.62) #first two terms N/A
#I1_6ns = (2.99, 2.75, 2.55, 2.43, 2.2, 2.08, 1.97, 1.9, 1.81, 1.69) #first three terms N/A

#500 Volts
#I1_7ew = (2.85, 2.67, 2.49, 2.34, 2.18, 2.07, 1.95, 1.88, 1.78, 1.71) #first three terms N/A
#I1_7ns = (2.85, 2.6, 2.44, 2.27, 2.2, 2.08, 1.99, 1.89, 1.78) #first four terms N/A

# What was used in chauv function 

In [7]:
def chauv(array):
    print(len(array))
    mu, sigma = scipy.stats.norm.fit(array)
    print(array)
    som = abs(mu+(2*sigma))
    optloc = np.where(som >= array)
    #opt = array[optloc]
    print(optloc)
    #print(len(opt))

It is determined that trials 1 from 200, 250, and 300 volts on the east-west oriented data should be thrown out. 

In [8]:
#200 Volts
I1_1ew = (10, 2.13, 1.97, 1.81, 1.69, 1.58, 1.48, 1.4, 1.32, 1.25, 1.2, 1.12, 1.06)

#250 Volts
I1_2ew = (10, 2.39, 2.21, 2.03, 1.9, 1.77, 1.66, 1.56, 1.49, 1.4, 1.34, 1.27, 1.22)

#300 Volts
I1_3ew = (10, 2.62, 2.42, 2.22, 2.07, 1.94, 1.82, 1.71, 1.63, 1.54, 1.48, 1.4, 1.33)

#Using N/A place holder 10

### 200 Volts

In [9]:
t1_1ew = np.empty(len(I1_1ew))
for i in range(len(I1_1ew)):
    t1_1ew[i] = (np.array(em(V[0],I1_1ew[i],r[i])))/(10**11)
    av1_1ew = np.mean(t1_1ew)

#Gotta account for the NA
NA_1ew = (t1_1ew[1:13])
NAav_1ew = np.mean(NA_1ew)
print(NA_1ew)
print(NAav_1ew)

[1.79778823 1.7659897  1.78253988 1.76300535 1.7570593  1.76002855
 1.74232511 1.74819646 1.74966894 1.71340735 1.78405597 1.8147885 ]
1.7649044444113562


In [10]:
t1_1ns = np.empty(len(I1_1ns))
for i in range(len(I1_1ns)):
    t1_1ns[i] = (np.array(em(V[0],I1_1ns[i],r[i])))/(10**11)
    av1_1ns = np.mean(t1_1ns)
    
print(t1_1ns)
print(av1_1ns)

[1.64418598 1.56901843 1.53941498 1.45994473 1.42466036 1.48266726
 1.58414141 1.53819973 1.55411098 1.54551287 1.57907622 1.63483075
 1.6852036 ]
1.556997483528516


### 250 Volts

In [11]:
t1_2ew = np.empty(len(I1_2ew))
for i in range(len(I1_2ew)):
    t1_2ew[i] = (np.array(em(V[1],I1_2ew[i],r[i])))/(10**11)
    av1_2ew = np.mean(t1_2ew)

#Gotta account for the NA
NA_2ew = (t1_2ew[1:13])
NAav_2ew = np.mean(NA_2ew)
print(NA_2ew)
print(NAav_2ew)

[1.78489203 1.75406662 1.77139063 1.74353171 1.75010486 1.74878726
 1.75406662 1.71504522 1.74353171 1.71760595 1.73439132 1.71249022]
1.7441586783321406


In [12]:
t1_2ns = np.empty(len(I1_2ns))
for i in range(len(I1_2ns)):
    t1_2ns[i] = (np.array(em(V[1],I1_2ns[i],r[i])))/(10**11)
    av1_2ns = np.mean(t1_2ns)
    
print(t1_2ns)
print(av1_2ns)

[1.58483742 1.50820736 1.46285035 1.39198788 1.31234742 1.39855717
 1.45482375 1.47705762 1.58483742 1.51880984 1.55129683 1.51243499
 1.63127708]
1.491486548523407


### 300 Volts

In [13]:
t1_3ew = np.empty(len(I1_3ew))
for i in range(len(I1_3ew)):
    t1_3ew[i] = (np.array(em(V[2],I1_3ew[i],r[i])))/(10**11)
    av1_3ew = np.mean(t1_3ew)

#Gotta account for the NA
NA_3ew = (t1_3ew[1:13])
NAav_3ew = np.mean(NA_3ew)
print(NA_3ew)
print(NAav_3ew)

[1.78232302 1.75542042 1.77738584 1.76269676 1.74818903 1.7457885
 1.75179913 1.71970578 1.72912235 1.68962741 1.71269373 1.72912235]
1.7419895259448663


In [14]:
t1_3ns = np.empty(len(I1_3ns))
for i in range(len(I1_3ns)):
    t1_3ns[i] = (np.array(em(V[2],I1_3ns[i],r[i])))/(10**11)
    av1_3ns = np.mean(t1_3ns)

#Gotta account for the NA
NA_3ns = (t1_3ns[1:13])
NAav_3ns = np.mean(NA_3ns)
print(NA_3ns)
print(NAav_3ns)

[1.57173959 1.46392939 1.40154694 1.33341207 1.33501425 1.4172017
 1.49669418 1.50914463 1.48816467 1.52077576 1.6188656  1.62962573]
1.4821762088286403


### 350 Volts

In [15]:
t1_4ew = np.empty(len(I1_4ew))
for i in range(len(I1_4ns)):
    t1_4ew[i] = (np.array(em(V[3],I1_4ew[i],r[i])))/(10**11)
    av1_4ew = np.mean(t1_4ew)

#Gotta account for the NA
NA_4ew = (t1_4ew[1:13])
NAav_4ew = np.mean(NA_4ew)
print(NA_4ew)
print(NAav_4ew)

[2.74578226 1.74725416 1.77423838 1.7406043  1.75730064 1.73839611
 1.7651746  1.7406043  1.73619212 1.70791762 1.71762627 1.72088089]
1.8243309706007176


In [16]:
t1_4ns = np.empty(len(I1_4ns))
for i in range(len(I1_3ns)):
    t1_4ns[i] = (np.array(em(V[3],I1_4ns[i],r[i])))/(10**11)
    av1_4ns = np.mean(t1_4ns)

#Gotta account for the NA
NA_4ns = (t1_4ns[1:13])
NAav_4ns = np.mean(NA_4ns)
print(NA_4ns)
print(NAav_4ns)

[1.90123002 1.50820526 1.62213506 1.54265668 1.5028712  1.51536162
 1.50909702 1.59174674 1.52709981 1.56691339 1.65135759 1.72088089]
1.5966296068269559


### 400 Volts

In [17]:
t1_5ew = np.empty(len(I1_5ew))
for i in range(len(I1_5ns)):
    t1_5ew[i] = (np.array(em(V[4],I1_5ew[i],r[i])))/(10**11)
    av1_5ew = np.mean(t1_5ew)

#Gotta account for the NA
NA_5ew = (t1_5ew[2:13])
NAav_5ew = np.mean(NA_5ew)
print(NA_5ew)
print(NAav_5ew)

[1.79941961 1.78215909 1.76303621 1.780019   1.76514574 1.77788277
 1.74214734 1.74525693 1.83470151 1.74837485 1.71959551]
1.7688853228209291


In [18]:
t1_5ns = np.empty(len(I1_5ns))
for i in range(len(I1_5ns)):
    t1_5ns[i] = (np.array(em(V[4],I1_5ns[i],r[i])))/(10**11)
    av1_5ns = np.mean(t1_4ns)

#Gotta account for the NA
NA_5ns = (t1_5ns[2:13])
NAav_5ns = np.mean(NA_5ns)
print(NA_5ns)
print(NAav_5ns)

[1.60762559 1.60213413 1.59848878 1.53580043 1.52302876 1.4638877
 1.4081257  1.42329119 1.52302876 1.54873343 1.47996542]
1.519464534674799


### 450 Volts

In [19]:
t1_6ew = np.empty(len(I1_6ew))
for i in range(len(I1_6ns)):
    t1_6ew[i] = (np.array(em(V[5],I1_6ew[i],r[i])))/(10**11)
    av1_6ew = np.mean(t1_6ew)

#Gotta account for the NA
NA_6ew = (t1_6ew[2:13])
NAav_6ew = np.mean(NA_6ew)
print(NA_6ew)
print(NAav_6ew)

[1.77198118 1.78912359 1.76998063 1.78709395 1.77599245 1.77599245
 1.7659897  1.7780032  1.7521272  1.74232511 1.74819646]
1.7688005378745073


In [20]:
t1_6ns = np.empty(len(I1_6ns))
for i in range(len(I1_6ns)):
    t1_6ns[i] = (np.array(em(V[5],I1_6ns[i],r[i])))/(10**11)
    av1_6ns = np.mean(t1_6ns)

#Gotta account for the NA
NA_6ns = (t1_6ns[3:13])
NAav_6ns = np.mean(NA_6ns)
print(NA_6ns)
print(NAav_6ns)

[1.46972657 1.49811161 1.51775876 1.46897064 1.58753176 1.58414141
 1.58498798 1.53779497 1.53698592 1.60637471]
1.5392384332243414


### 500 Volts

In [21]:
t1_7ew = np.empty(len(I1_7ew))
for i in range(len(I1_7ew)):
    t1_7ew[i] = (np.array(em(V[6],I1_7ew[i],r[i])))/(10**11)
    av1_7ew = np.mean(t1_6ew)

#Gotta account for the NA
NA_7ew = (t1_7ew[3:13])
NAav_7ew = np.mean(NA_7ew)
print(NA_7ew)
print(NAav_7ew)

[1.7974081  1.76581225 1.76865003 1.76015713 1.79643823 1.77720455
 1.7974081  1.74520894 1.76581225 1.74335381]
1.7717453379237056


In [22]:
t1_7ns = np.empty(len(I1_7ns))
for i in range(len(I1_7ns)):
    t1_7ns[i] = (np.array(em(V[6],I1_7ns[i],r[i])))/(10**11)
    av1_7ns = np.mean(t1_7ns)

#Gotta account for the NA
NA_7ns = (t1_7ns[4:13])
NAav_7ns = np.mean(NA_7ns)
print(NA_7ns)
print(NAav_7ns)

[1.54980596 1.62216081 1.61883841 1.65681326 1.57337682 1.57975321
 1.55760371 1.56624941 1.60893223]
1.592614869311932


Okay, so now we have figured out what data is relevant, calculated e/m for each trial on each voltage at each radius, and averaged them for all voltages for both east-west and north-south data. We need to back track a little and figure out some error now. I'm going to redefine the raw data first without the placeholders (10) so we can find standard deviation on the raw data (the currents)

### Standard Deviation

In [23]:
#200 Volts
I1_1ew = (2.13, 1.97, 1.81, 1.69, 1.58, 1.48, 1.4, 1.32, 1.25, 1.2, 1.12, 1.06)
I1_1ns = (2.45, 2.28, 2.11, 2, 1.88, 1.72, 1.56, 1.49, 1.4, 1.33, 1.25, 1.17, 1.1)

#250 Volts
I1_2ew = (2.39, 2.21, 2.03, 1.9, 1.77, 1.66, 1.56, 1.49, 1.4, 1.34, 1.27, 1.22)
I1_2ns = (2.79, 2.6, 2.42, 2.29, 2.19, 1.98, 1.82, 1.7, 1.55, 1.5, 1.41, 1.36, 1.25)

#300 Volts
I1_3ew = (2.62, 2.42, 2.22, 2.07, 1.94, 1.82, 1.71, 1.63, 1.54, 1.48, 1.4, 1.33)
I1_3ns = ((2.79,2.65, 2.5, 2.38, 2.22, 2.02, 1.85, 1.74, 1.66, 1.56, 1.44, 1.37))

#350 Volts
I1_4ew = (2.28, 2.62, 2.4, 2.25, 2.09, 1.97, 1.84, 1.75, 1.66, 1.59, 1.51, 1.44)
I1_4ns = (2.74, 2.82, 2.51, 2.39, 2.26, 2.11, 1.99, 1.83, 1.77, 1.66, 1.54, 1.44)

#400 Volts
I1_5ew = (2.76, 2.56, 2.39, 2.22, 2.09, 1.96, 1.87, 1.77, 1.64, 1.6, 1.54)
I1_5ns = (2.92, 2.7, 2.51, 2.39, 2.25, 2.16, 2.08, 1.96, 1.8, 1.7, 1.66) 

#450 Volts
I1_6ew = (2.95, 2.71, 2.53, 2.35, 2.21, 2.08, 1.97, 1.86, 1.78, 1.7, 1.62) 
I1_6ns = (2.99, 2.75, 2.55, 2.43, 2.2, 2.08, 1.97, 1.9, 1.81, 1.69)

#500 Volts
I1_7ew = (2.85, 2.67, 2.49, 2.34, 2.18, 2.07, 1.95, 1.88, 1.78, 1.71)
I1_7ns = (2.85, 2.6, 2.44, 2.27, 2.2, 2.08, 1.99, 1.89, 1.78)

In [24]:
#East-West:
std1_1ew = np.std(I1_1ew)
std1_2ew = np.std(I1_2ew)
std1_3ew = np.std(I1_3ew)
std1_4ew = np.std(I1_4ew)
std1_5ew = np.std(I1_5ew)
std1_6ew = np.std(I1_6ew)
std1_7ew = np.std(I1_7ew)

#North-South:
std1_1ns = np.std(I1_1ns)
std1_2ns = np.std(I1_2ns)
std1_3ns = np.std(I1_3ns)
std1_4ns = np.std(I1_4ns)
std1_5ns = np.std(I1_5ns)
std1_6ns = np.std(I1_6ns)
std1_7ns = np.std(I1_7ns)

In [25]:
print(std1_1ew, std1_2ew, std1_3ew, std1_4ew, std1_5ew, std1_6ew, std1_7ew)
ewstd = (std1_1ew, std1_2ew, std1_3ew, std1_4ew, std1_5ew, std1_6ew, std1_7ew)

0.3278327402129866 0.363784124019849 0.39643901030157075 0.36398260031673674 0.38821907421812346 0.41365334630471795 0.36676422944447573


In [26]:
print(std1_1ns, std1_2ns, std1_3ns, std1_4ns, std1_5ns, std1_6ns, std1_7ns)
nsstd = (std1_1ns, std1_2ns, std1_3ns, std1_4ns, std1_5ns, std1_6ns, std1_7ns)

0.42188503439742997 0.48644952060278007 0.46519709084788274 0.4416792451039052 0.39055374970029244 0.40716212986966266 0.32761766334148307


### Error Prop

In [27]:
stdr = 0.0005
stdV = 1

#Partial derivatives:

#current
#-((2*(a**2)*cons*(V**2))/((N**2)*(r**2)*(I**3)))

#Voltage; 1
#(2*(a**2)*cons*V)/((N**2)*(r**2)*(I**2))

#radius; 0.0005
#-((2*(a**2)*cons*(V**2))/((N**2)*(r**3)*(I**2)))

In [28]:
def getprop(V,r,I,std):
    part1a = -((2*(a**2)*cons*(V**2))/((N**2)*(r**2)*(I**3)))
    part1b = (part1a**2)*(std**2)
    
    part2a = (2*(a**2)*cons*V)/((N**2)*(r**2)*(I**2))
    part2b = (part2a**2)*(stdV**2)
    
    part3a = -((2*(a**2)*cons*(V**2))/((N**2)*(r**3)*(I**2)))
    part3b = (part3a**2)*(stdr**2)
    
    partc = part1b + part2b + part3b
    
    partd = np.sqrt(partc)
    
    return partd

#### East-West

In [29]:
prop1_1ew = np.empty(len(I1_1ew))
for i in range(len(I1_1ew)):
    prop1_1ew[i] = (np.array(getprop(V[0],r[i],I1_1ew[i],ewstd[0]))/(10E13))
                    
print(prop1_1ew)
print(np.mean(prop1_1ew))

[0.13511946 0.14079323 0.15226222 0.15920382 0.16784967 0.17779655
 0.1845389  0.19496215 0.20473333 0.20765349 0.23046127 0.24654815]
0.1834935195264037


In [30]:
prop1_2ew = np.empty(len(I1_2ew))
for i in range(len(I1_2ew)):
    prop1_2ew[i] = (np.array(getprop(V[1],r[i],I1_2ew[i],ewstd[1]))/(10E13))
                    
print(prop1_2ew)
print(np.mean(prop1_2ew))

[0.16583554 0.17290381 0.18712581 0.19424551 0.20699479 0.21846129
 0.23124899 0.23502387 0.25265377 0.25855834 0.27405801 0.28038142]
0.22312426162687912


In [31]:
prop1_3ew = np.empty(len(I1_3ew))
for i in range(len(I1_3ew)):
    prop1_3ew[i] = (np.array(getprop(V[2],r[i],I1_3ew[i],ewstd[2]))/(10E13))
                    
print(prop1_3ew)
print(np.mean(prop1_3ew))

[0.19754345 0.20664166 0.22451165 0.23570368 0.24669303 0.2601166
 0.27551726 0.28170174 0.29787587 0.30114683 0.32103959 0.33959179]
0.2656735964092763


In [32]:
prop1_4ew = np.empty(len(I1_4ew))
for i in range(len(I1_4ew)):
    prop1_4ew[i] = (np.array(getprop(V[3],r[i],I1_4ew[i],ewstd[3]))/(10E13))
                    
print(prop1_4ew)
print(np.mean(prop1_4ew))

[0.37423591 0.20398054 0.22242649 0.22966129 0.24678524 0.25650639
 0.27651382 0.28459176 0.29732006 0.30359432 0.31982532 0.3344333 ]
0.2791562039439827


In [33]:
prop1_5ew = np.empty(len(I1_5ew))
for i in range(len(I1_5ew)):
    prop1_5ew[i] = (np.array(getprop(V[4],r[i],I1_5ew[i],ewstd[4]))/(10E13))
                    
print(prop1_5ew)
print(np.mean(prop1_5ew))

[0.29455493 0.304181   0.31350813 0.33285306 0.34364081 0.36269823
 0.36688703 0.3831019  0.42944293 0.41499621 0.41997222]
0.36053058608517125


In [34]:
prop1_6ew = np.empty(len(I1_6ew))
for i in range(len(I1_6ew)):
    prop1_6ew[i] = (np.array(getprop(V[5],r[i],I1_6ew[i],ewstd[5]))/(10E13))
                    
print(prop1_6ew)
print(np.mean(prop1_6ew))

[0.32531593 0.34574522 0.35637325 0.37839136 0.39192547 0.40923525
 0.423154   0.44518082 0.45295526 0.46656783 0.48650674]
0.4073955579010376


In [35]:
prop1_7ew = np.empty(len(I1_7ew))
for i in range(len(I1_7ew)):
    prop1_7ew[i] = (np.array(getprop(V[6],r[i],I1_7ew[i],ewstd[6]))/(10E13))
                    
print(prop1_7ew)
print(np.mean(prop1_7ew))

[0.3956482  0.39637619 0.40968649 0.4199455  0.44727543 0.45474745
 0.47780175 0.47211707 0.49597068 0.50194461]
0.4471513355897546


#### North-South

In [36]:
prop1_1ns = np.empty(len(I1_1ns))
for i in range(len(I1_1ns)):
    prop1_1ns[i] = (np.array(getprop(V[0],r[i],I1_1ns[i],nsstd[0]))/(10E13))
                    
print(prop1_1ns)
print(np.mean(prop1_1ns))

[0.11405891 0.11673224 0.123585   0.12354746 0.128172   0.14571358
 0.17157774 0.17439046 0.18748339 0.19623116 0.21329729 0.2359034
 0.25862628]
0.16840914672092414


In [37]:
prop1_2ns = np.empty(len(I1_2ns))
for i in range(len(I1_2ns)):
    prop1_2ns[i] = (np.array(getprop(V[1],r[i],I1_2ns[i],nsstd[1]))/(10E13))
                    
print(prop1_2ns)
print(np.mean(prop1_2ns))

[0.13910402 0.14178649 0.1475589  0.14825876 0.14607603 0.17207542
 0.19465686 0.2115268  0.24886742 0.24642319 0.26772881 0.27059927
 0.31751694]
0.20401376277602815


In [38]:
prop1_3ns = np.empty(len(I1_3ns))
for i in range(len(I1_3ns)):
    prop1_3ns[i] = (np.array(getprop(V[2],r[i],I1_3ns[i],nsstd[2]))/(10E13))
                    
print(prop1_3ns)
print(np.mean(prop1_3ns))

[0.19166268 0.18451602 0.18440993 0.18194868 0.19315644 0.22320195
 0.25525923 0.2716882  0.27903912 0.30170264 0.34613555 0.36454738]
0.24810565070959797


In [39]:
prop1_4ns = np.empty(len(I1_4ns))
for i in range(len(I1_4ns)):
    prop1_4ns[i] = (np.array(getprop(V[3],r[i],I1_4ns[i],nsstd[3]))/(10E13))
                    
print(prop1_4ns)
print(np.mean(prop1_4ns))

[0.26161277 0.1981397  0.23558008 0.2322721  0.23667269 0.25317209
 0.26512491 0.30187057 0.29752255 0.32363786 0.36575425 0.40572167]
0.281423436509247


In [40]:
prop1_5ns = np.empty(len(I1_5ns))
for i in range(len(I1_5ns)):
    prop1_5ns[i] = (np.array(getprop(V[4],r[i],I1_5ns[i],nsstd[4]))/(10E13))
                    
print(prop1_5ns)
print(np.mean(prop1_5ns))

[0.25050211 0.26102077 0.27241615 0.26851595 0.2771985  0.2727464
 0.26831966 0.28392755 0.32682768 0.34810559 0.33737746]
0.2879052546352401


In [41]:
prop1_6ns = np.empty(len(I1_6ns))
for i in range(len(I1_6ns)):
    prop1_6ns[i] = (np.array(getprop(V[5],r[i],I1_6ns[i],nsstd[5]))/(10E13))
                    
print(prop1_6ns)
print(np.mean(prop1_6ns))

[0.30771793 0.32582951 0.34267877 0.33700073 0.3910862  0.40284313
 0.41653808 0.41114369 0.42407732 0.46745603]
0.382637137838767


In [42]:
prop1_7ns = np.empty(len(I1_7ns))
for i in range(len(I1_7ns)):
    prop1_7ns[i] = (np.array(getprop(V[6],r[i],I1_7ns[i],nsstd[6]))/(10E13))
                    
print(prop1_7ns)
print(np.mean(prop1_7ns))

[0.35448283 0.38407253 0.38942709 0.41126419 0.38912965 0.40068507
 0.40185681 0.41527319 0.44320115]
0.3988213887788748


### Experimenter Two

In [43]:
r2 = (0.0275, 0.03, 0.0325, 0.035, 0.0375, 0.04, 0.0425, 0.045, 0.0475, 0.05, 0.0525, 0.055)

In [44]:
#r2[0]
I2a_1 = (2.61, 2.64, 2.62, 2.58, 2.65, 2.63, 2.61, 2.59) #250 V
I2b_1 = (2.99) #400 V

#r2[1]
I2b_2 = (2.92, 2.88, 2.92, 2.9) #400 V

#r2[2]
I2a_3 = (2.29, 2.29, 2.34, 2.27, 2.28, 2.27, 2.3, 2.26) #250 V
I2b_3 = (2.75, 2.77, 2.69, 2.67) #400 V

#r2[3]
I2b_4 = (2.44, 2.51, 2.52, 2.52) #400 V

#r2[4]
I2a_5 = (2.01, 2.02, 2.04, 1.96, 1.96, 1.95, 1.99, 2.01) #250 V
I2b_5 = (2.41, 2.36, 2.34, 2.36) #400 V

#r2[5]
I2b_6 = (2.25, 2.3, 2.19, 2.24) #400 V

#r2[6]
I2b_7 = (2.18, 2.14, 2.17, 2.16) #400 V

#r2[7]
I2b_8 = (2.1, 2.05, 2.05, 2.07) #400 V

#r2[8]
I2a_9 = (1.53, 1.52, 1.49, 1.52, 1.49, 1.5, 1.52, 1.48) #250 V
I2b_9 = (1.99, 1.96, 1.94, 1.97) #400 V

#r2[9]
I2b_10 = (2.01, 1.81, 1.82, 1.83) #400 V

#r2[10]
I2a_11 = (1.35, 1.35, 1.37, 1.32, 1.38, 1.36, 1.35, 1.22) #250 V
I2b_11 = (1.67, 1.74, 1.71, 1.71) #400 V

#r2[11]
I2b_12 = (1.62, 1.65, 1.67, 1.68) #400 V

Doing Chuav on this, there is no major outliers that can be ignored for the data from experimenter 2

### 250 Volts

In [45]:
t2a_1 = np.empty(len(I2a_1))
for i in range(len(I2a_1)):
    t2a_1[i] = (np.array(em(250,I2a_1[i],r2[0])))/(10**11)
    av2a_1 = np.mean(t2a_1)
    
print(t2a_1)
print(av2a_1)

[1.49667236 1.46285035 1.48526918 1.53168105 1.4518308  1.47399583
 1.49667236 1.51987623]
1.4898560203000417


In [46]:
t2a_3 = np.empty(len(I2a_3))
for i in range(len(I2a_3)):
    t2a_3[i] = (np.array(em(250,I2a_3[i],r2[2])))/(10**11)
    av2a_3 = np.mean(t2a_3)
    
print(t2a_3)
print(av2a_3)

[1.39198788 1.39198788 1.33313676 1.41662435 1.40422508 1.41662435
 1.37990995 1.42918859]
1.3954606048662719


In [47]:
t2a_5 = np.empty(len(I2a_5))
for i in range(len(I2a_5)):
    t2a_5[i] = (np.array(em(250,I2a_5[i],r2[4])))/(10**11)
    av2a_5 = np.mean(t2a_5)
    
print(t2a_5)
print(av2a_5)

[1.35712075 1.34371717 1.31749893 1.42724478 1.42724478 1.44192072
 1.38453664 1.35712075]
1.382050561559368


In [48]:
t2a_9 = np.empty(len(I2a_9))
for i in range(len(I2a_9)):
    t2a_9[i] = (np.array(em(250,I2a_9[i],r2[8])))/(10**11)
    av2a_9 = np.mean(t2a_9)
    
print(t2a_9)
print(av2a_9)

[1.4598326  1.47910411 1.53926496 1.47910411 1.53926496 1.51880984
 1.47910411 1.56013611]
1.5068276037294883


In [49]:
t2a_11 = np.empty(len(I2a_11))
for i in range(len(I2a_11)):
    t2a_11[i] = (np.array(em(250,I2a_11[i],r2[10])))/(10**11)
    av2a_11 = np.mean(t2a_11)
    
print(t2a_11)
print(av2a_11)

[1.53492442 1.53492442 1.49043623 1.60548655 1.46891397 1.51243499
 1.53492442 1.87946772]
1.5701890911202194


### 400 Volts

In [50]:
# Only one value so the loop has to go
t2b_1 = (np.array(em(400,I2b_1,r2[0])))/(10**11)
av2b_1 = np.mean(t2b_1)
    
print(t2b_1)
print(av2b_1)

1.8246743139123325
1.8246743139123325


In [51]:
t2b_2 = np.empty(len(I2b_2))
for i in range(len(I2b_2)):
    t2b_2[i] = (np.array(em(400,I2b_2[i],r2[1])))/(10**11)
    av2b_2 = np.mean(t2b_2)
    
print(t2b_2)
print(av2b_2)

[1.60762559 1.65259197 1.60762559 1.6298762 ]
1.624429836411745


In [52]:
t2b_3 = np.empty(len(I2b_3))
for i in range(len(I2b_3)):
    t2b_3[i] = (np.array(em(400,I2b_3[i],r2[2])))/(10**11)
    av2b_3 = np.mean(t2b_3)
    
print(t2b_3)
print(av2b_3)

[1.54440434 1.52218298 1.61406805 1.63833941]
1.579748695593433


In [53]:
t2b_4 = np.empty(len(I2b_4))
for i in range(len(I2b_4)):
    t2b_4[i] = (np.array(em(400,I2b_4[i],r2[3])))/(10**11)
    av2b_4 = np.mean(t2b_4)
    
print(t2b_4)
print(av2b_4)

[1.69152095 1.59848878 1.58582753 1.58582753]
1.6154161961371574


In [54]:
t2b_5 = np.empty(len(I2b_5))
for i in range(len(I2b_5)):
    t2b_5[i] = (np.array(em(400,I2b_5[i],r2[4])))/(10**11)
    av2b_5 = np.mean(t2b_5)
    
print(t2b_5)
print(av2b_5)

[1.51041574 1.57509438 1.60213413 1.57509438]
1.5656846563668996


In [55]:
t2b_6 = np.empty(len(I2b_6))
for i in range(len(I2b_6)):
    t2b_6[i] = (np.array(em(400,I2b_6[i],r2[5])))/(10**11)
    av2b_6 = np.mean(t2b_6)
    
print(t2b_6)
print(av2b_6)

[1.52302876 1.45752988 1.60762559 1.53665758]
1.531210453897918


In [56]:
t2b_7 = np.empty(len(I2b_7))
for i in range(len(I2b_7)):
    t2b_7[i] = (np.array(em(400,I2b_7[i],r2[6])))/(10**11)
    av2b_7 = np.mean(t2b_7)
    
print(t2b_7)
print(av2b_7)

[1.43715058 1.49137794 1.45042673 1.4638877 ]
1.4607107383670388


In [57]:
t2b_8 = np.empty(len(I2b_8))
for i in range(len(I2b_8)):
    t2b_8[i] = (np.array(em(400,I2b_8[i],r2[7])))/(10**11)
    av2b_8 = np.mean(t2b_8)
    
print(t2b_8)
print(av2b_8)

[1.38143198 1.4496407  1.4496407  1.42176364]
1.4256192548685434


In [58]:
t2b_9 = np.empty(len(I2b_9))
for i in range(len(I2b_9)):
    t2b_9[i] = (np.array(em(400,I2b_9[i],r2[8])))/(10**11)
    av2b_9 = np.mean(t2b_9)
    
print(t2b_9)
print(av2b_9)

[1.38070135 1.42329119 1.45278867 1.40887821]
1.4164148544540212


In [59]:
t2b_10 = np.empty(len(I2b_10))
for i in range(len(I2b_10)):
    t2b_10[i] = (np.array(em(400,I2b_10[i],r2[9])))/(10**11)
    av2b_10 = np.mean(t2b_10)
    
print(t2b_10)
print(av2b_10)

[1.22140867 1.5062462  1.48973952 1.4735027 ]
1.4227242714280635


In [60]:
t2b_11 = np.empty(len(I2b_11))
for i in range(len(I2b_11)):
    t2b_11[i] = (np.array(em(400,I2b_11[i],r2[10])))/(10**11)
    av2b_11 = np.mean(t2b_11)
    
print(t2b_11)
print(av2b_11)

[1.60487634 1.47834576 1.53067255 1.53067255]
1.5361418009785015


In [61]:
t2b_12 = np.empty(len(I2b_12))
for i in range(len(I2b_12)):
    t2b_12[i] = (np.array(em(400,I2b_12[i],r2[11])))/(10**11)
    av2b_12 = np.mean(t2b_12)
    
print(t2b_12)
print(av2b_12)

[1.55395241 1.49795875 1.46229435 1.44493789]
1.4897858517118823


Okay. Now let's do some error

### Standrad Deviation

In [62]:
#250 V
std2a_1 = np.std(I2a_1)
std2a_3 = np.std(I2a_3)
std2a_5 = np.std(I2a_5)
std2a_9 = np.std(I2a_9)
std2a_11 = np.std(I2a_11)

#400 V
std2b_1 = np.std(I2b_1)
std2b_2 = np.std(I2b_2)
std2b_3 = np.std(I2b_3)
std2b_4 = np.std(I2b_4)
std2b_5 = np.std(I2b_5)
std2b_6 = np.std(I2b_6)
std2b_7 = np.std(I2b_7)
std2b_8 = np.std(I2b_8)
std2b_9 = np.std(I2b_9)
std2b_10 = np.std(I2b_10)
std2b_11 = np.std(I2b_11)
std2b_12 = np.std(I2b_12)

In [63]:
print(std2a_1, std2a_3, std2a_5, std2a_9, std2a_11)

std2a = (std2a_1, std2a_3, std2a_5, std2a_9, std2a_11)
r2a = (0.0275, 0.0325, 0.0375, 0.0475, 0.0525)

0.0223257138743647 0.023318447632722023 0.030720514318611263 0.017275343701356582 0.04736823830374105


In [64]:
print(std2b_1, std2b_2, std2b_3, std2b_4, std2b_5, std2b_6, std2b_7, std2b_8, std2b_9, std2b_10, std2b_11, std2b_12)

std2b = (std2b_1, std2b_2, std2b_3, std2b_4, std2b_5, std2b_6, std2b_7, std2b_8, std2b_9, std2b_10, std2b_11, std2b_12)

0.0 0.016583123951777013 0.041231056256176644 0.03344772040064914 0.025860201081971616 0.03905124837953322 0.014790199457749025 0.02046338192968123 0.018027756377319962 0.0825757228245686 0.024874685927665518 0.022912878474779134


### Propogation of Error

In [65]:
def getprop(V,r,I,std):
    part1a = -((2*(a**2)*cons*(V**2))/((N**2)*(r**2)*(I**3)))
    part1b = (part1a**2)*(std**2)
    
    part2a = (2*(a**2)*cons*V)/((N**2)*(r**2)*(I**2))
    part2b = (part2a**2)*(stdV**2)
    
    part3a = -((2*(a**2)*cons*(V**2))/((N**2)*(r**3)*(I**2)))
    part3b = (part3a**2)*(stdr**2)
    
    partc = part1b + part2b + part3b
    
    partd = np.sqrt(partc)
    
    return partd

#### 250 Volts

In [66]:
prop2a_1 = np.empty(len(I2a_1))
for i in range(len(I2a_1)):
    prop2a_1[i] = (np.array(getprop(250,r2a[0],I2a_1[i],std2a[0]))/(10E12))
                    
print(prop2a_1)
print(np.mean(prop2a_1))

[0.15331725 0.14955712 0.15204806 0.15722306 0.14833486 0.15079477
 0.15331725 0.15590447]
0.15256210675542176


In [67]:
prop2a_2 = np.empty(len(I2a_3))
for i in range(len(I2a_3)):
    prop2a_2[i] = (np.array(getprop(250,r2a[1],I2a_3[i],std2a[1]))/(10E12))
                    
print(prop2a_2)
print(np.mean(prop2a_2))

[0.1313889  0.1313889  0.12505764 0.13405816 0.13271336 0.13405816
 0.13008436 0.13542371]
0.1317716482134126


In [68]:
prop2a_3 = np.empty(len(I2a_5))
for i in range(len(I2a_5)):
    prop2a_3[i] = (np.array(getprop(250,r2a[2],I2a_5[i],std2a[2]))/(10E12))
                    
print(prop2a_3)
print(np.mean(prop2a_3))

[0.14027888 0.13851801 0.1350924  0.14959603 0.14959603 0.15156805
 0.14390067 0.14027888]
0.1436036169226656


In [69]:
prop2a_4 = np.empty(len(I2a_9))
for i in range(len(I2a_9)):
    prop2a_4[i] = (np.array(getprop(250,r2a[3],I2a_9[i],std2a[3]))/(10E12))
                    
print(prop2a_4)
print(np.mean(prop2a_4))

[0.11639629 0.11832248 0.12439237 0.11832248 0.12439237 0.12231895
 0.11832248 0.12651811]
0.12112318879496575


In [70]:
prop2a_5 = np.empty(len(I2a_11))
for i in range(len(I2a_11)):
    prop2a_5[i] = (np.array(getprop(250,r2a[4],I2a_11[i],std2a[4]))/(10E12))
                    
print(prop2a_5)
print(np.mean(prop2a_5))

[0.28071094 0.28071094 0.26891516 0.29976182 0.26326934 0.27472697
 0.28071094 0.37755721]
0.2907954122963543


### 400 Volts

In [71]:
#Only one value so no need for the for loop
prop2b_1 = (np.array(getprop(400,r2[0],I2b_1,std2b[0]))/(10E12))
                    
print(prop2b_1)
print(np.mean(prop2b_1))

0.26790435230669596
0.26790435230669596


In [72]:
prop2b_2 = np.empty(len(I2b_2))
for i in range(len(I2b_2)):
    prop2b_2[i] = (np.array(getprop(400,r2[1],I2b_2[i],std2b[1]))/(10E12))
                    
print(prop2b_2)
print(np.mean(prop2b_2))

[0.22872368 0.23545632 0.22872368 0.23205296]
0.2312391621102013


In [73]:
prop2b_3 = np.empty(len(I2b_3))
for i in range(len(I2b_3)):
    prop2b_3[i] = (np.array(getprop(400,r2[2],I2b_3[i],std2b[2]))/(10E12))
                    
print(prop2b_3)
print(np.mean(prop2b_3))

[0.26720742 0.26245059 0.28227117 0.28757291]
0.2748755201960697


In [74]:
prop2b_4 = np.empty(len(I2b_4))
for i in range(len(I2b_4)):
    prop2b_4[i] = (np.array(getprop(400,r2[3],I2b_4[i],std2b[3]))/(10E12))
                    
print(prop2b_4)
print(np.mean(prop2b_4))

[0.27004835 0.25186281 0.24941445 0.24941445]
0.2551850141403588


In [75]:
prop2b_5 = np.empty(len(I2b_5))
for i in range(len(I2b_5)):
    prop2b_5[i] = (np.array(getprop(400,r2[4],I2b_5[i],std2b[4]))/(10E12))
                    
print(prop2b_5)
print(np.mean(prop2b_5))

[0.20899917 0.21973753 0.22426601 0.21973753]
0.21818505837288374


In [76]:
prop2b_6 = np.empty(len(I2b_6))
for i in range(len(I2b_6)):
    prop2b_6[i] = (np.array(getprop(400,r2[5],I2b_6[i],std2b[5]))/(10E12))
                    
print(prop2b_6)
print(np.mean(prop2b_6))

[0.26238127 0.24756524 0.28190744 0.26549748]
0.26433785678539967


In [77]:
prop2b_7 = np.empty(len(I2b_7))
for i in range(len(I2b_7)):
    prop2b_7[i] = (np.array(getprop(400,r2[6],I2b_7[i],std2b[6]))/(10E12))
                    
print(prop2b_7)
print(np.mean(prop2b_7))

[0.15876457 0.16550376 0.16040975 0.16208098]
0.16168976469472046


In [78]:
prop2b_8 = np.empty(len(I2b_8))
for i in range(len(I2b_8)):
    prop2b_8[i] = (np.array(getprop(400,r2[7],I2b_8[i],std2b[7]))/(10E12))
                    
print(prop2b_8)
print(np.mean(prop2b_8))

[0.16564707 0.17563036 0.17563036 0.17153186]
0.17210991381347518


In [79]:
prop2b_9 = np.empty(len(I2b_9))
for i in range(len(I2b_9)):
    prop2b_9[i] = (np.array(getprop(400,r2[8],I2b_9[i],std2b[8]))/(10E12))
                    
print(prop2b_9)
print(np.mean(prop2b_9))

[0.15586526 0.16169129 0.16575826 0.15971357]
0.1607570933766013


In [80]:
prop2b_10 = np.empty(len(I2b_10))
for i in range(len(I2b_10)):
    prop2b_10[i] = (np.array(getprop(400,r2[9],I2b_10[i],std2b[9]))/(10E12))
                    
print(prop2b_10)
print(np.mean(prop2b_10))

[0.41387037 0.56360015 0.55451013 0.54561687]
0.5193993810956878


In [81]:
prop2b_11 = np.empty(len(I2b_11))
for i in range(len(I2b_11)):
    prop2b_11[i] = (np.array(getprop(400,r2[10],I2b_11[i],std2b[10]))/(10E12))
                    
print(prop2b_11)
print(np.mean(prop2b_11))

[0.22924542 0.2052967  0.21509962 0.21509962]
0.2161853403334436


In [82]:
prop2b_12 = np.empty(len(I2b_12))
for i in range(len(I2b_12)):
    prop2b_11[i] = (np.array(getprop(400,r2[11],I2b_12[i],std2b[11]))/(10E12))
                    
print(prop2b_12)
print(np.mean(prop2b_12))

[0.22924542 0.2052967  0.21509962 0.21509962]
0.2161853403334436
